[tools]
golangci-lint = "2.6.1"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "latest"
"vfox-pulumi:pulumi/pulumi-aws" = "latest"
"vfox-pulumi:pulumi/pulumi-azure" = "latest"
"vfox-pulumi:pulumi/pulumi-gcp" = "latest"