[tools]
golangci-lint = "2.6.1"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "1.2.4"
"vfox-pulumi:pulumi/pulumi-aws" = "7.16.0"
"vfox-pulumi:pulumi/pulumi-azure" = "6.31.0"
"vfox-pulumi:pulumi/pulumi-gcp" = "9.9.0"